"""
DMS FileManager — template-based document file management.

Composes the existing StorageManager with DMS-specific functionality:
- Template-based file naming using document metadata
- Dual-path storage (original + archive PDF/A)
- SHA-256 checksum computation
- Automatic rename-on-metadata-change

Sourced from Paperless-ngx file_handling.py — adapted for Synapse.
"""

import hashlib
import logging
import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Optional

from pathvalidate import sanitize_filename

from app.config.storage import StorageConfig, storage_config

logger = logging.getLogger(__name__)


class FileManager:
    """
    DMS file manager layered on top of StorageManager.

    Provides Paperless-style dual-path document storage:
    - originals_dir/ → the file exactly as uploaded
    - archive_dir/   → the PDF/A archive generated during parsing
    - thumbnail_dir/ → generated thumbnails

    File naming is template-based using document metadata.
    """

    def __init__(self, config: Optional[StorageConfig] = None):
        self.config = config or storage_config
        self.config.ensure_directories()

    # -----------------------------------------------------------------------
    # Path resolution
    # -----------------------------------------------------------------------

    def resolve_path(
        self,
        filename: str,
        *,
        created_date: Optional[datetime] = None,
        correspondent: Optional[str] = None,
        document_type: Optional[str] = None,
        title: Optional[str] = None,
        asn: Optional[int] = None,
        owner: Optional[str] = None,
        tags: Optional[str] = None,
    ) -> str:
        """
        Resolve a storage path from the filename template.

        Template variables:
            {created_year}   — document created year (YYYY)
            {created_month}  — document created month (MM)
            {created_day}    — document created day (DD)
            {correspondent}  — correspondent name or 'none'
            {document_type}  — document type name or 'none'
            {title}          — document title (sanitized)
            {asn}            — archive serial number or 'none'
            {owner}          — document owner username or 'none'
            {tags}           — comma-joined tag names or 'none'

        Returns:
            Relative path suitable for joining with originals_dir/archive_dir.
        """
        now = created_date or datetime.now()

        # Build substitution dict
        subs = {
            "created_year": now.strftime("%Y"),
            "created_month": now.strftime("%m"),
            "created_day": now.strftime("%d"),
            "correspondent": sanitize_filename(correspondent or "none"),
            "document_type": sanitize_filename(document_type or "none"),
            "title": sanitize_filename(title or Path(filename).stem),
            "asn": str(asn) if asn else "none",
            "owner": sanitize_filename(owner or "none"),
            "tags": sanitize_filename(tags or "none"),
        }

        try:
            relative = self.config.filename_format.format(**subs)
        except KeyError as e:
            logger.warning("Invalid filename format key %s, using default", e)
            relative = f"{subs['created_year']}/{subs['title']}"

        # Append the file extension
        ext = Path(filename).suffix
        if not relative.endswith(ext):
            relative = relative + ext

        return relative

    # -----------------------------------------------------------------------
    # Store operations
    # -----------------------------------------------------------------------

    def store_original(
        self,
        source_path: str,
        relative_path: str,
    ) -> str:
        """
        Copy a file into the originals directory.

        Returns:
            Absolute path to the stored original.
        """
        dest = self.config.originals_dir / relative_path
        dest.parent.mkdir(parents=True, exist_ok=True)

        shutil.copy2(source_path, dest)
        logger.info("Stored original: %s", dest)
        return str(dest)

    def store_archive(
        self,
        source_path: str,
        relative_path: str,
    ) -> str:
        """
        Copy a file into the archive directory.

        The archive copy is typically a PDF/A generated by the parser.

        Returns:
            Absolute path to the stored archive.
        """
        # Force .pdf extension for archive files
        archive_relative = Path(relative_path).with_suffix(".pdf")
        dest = self.config.archive_dir / archive_relative
        dest.parent.mkdir(parents=True, exist_ok=True)

        shutil.copy2(source_path, dest)
        logger.info("Stored archive: %s", dest)
        return str(dest)

    def store_thumbnail(
        self,
        source_path: str,
        document_id: int,
    ) -> str:
        """
        Store a thumbnail image.

        Returns:
            Absolute path to the stored thumbnail.
        """
        ext = Path(source_path).suffix or ".png"
        dest = self.config.thumbnail_dir / f"{document_id}{ext}"
        dest.parent.mkdir(parents=True, exist_ok=True)

        shutil.copy2(source_path, dest)
        logger.info("Stored thumbnail: %s", dest)
        return str(dest)

    # -----------------------------------------------------------------------
    # File operations
    # -----------------------------------------------------------------------

    def update_filename_and_move_files(
        self,
        old_relative: str,
        new_relative: str,
    ) -> tuple[Optional[str], Optional[str]]:
        """
        Rename/move files when document metadata changes.

        Moves both original and archive files.

        Returns:
            Tuple of (new_original_path, new_archive_path).
        """
        new_orig = None
        new_arch = None

        # Move original
        old_orig = self.config.originals_dir / old_relative
        if old_orig.exists():
            new_dest = self.config.originals_dir / new_relative
            new_dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(old_orig), str(new_dest))
            new_orig = str(new_dest)
            logger.info("Moved original: %s → %s", old_orig, new_dest)

        # Move archive
        old_archive_rel = Path(old_relative).with_suffix(".pdf")
        new_archive_rel = Path(new_relative).with_suffix(".pdf")
        old_arch = self.config.archive_dir / old_archive_rel
        if old_arch.exists():
            new_dest = self.config.archive_dir / new_archive_rel
            new_dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(old_arch), str(new_dest))
            new_arch = str(new_dest)
            logger.info("Moved archive: %s → %s", old_arch, new_dest)

        return new_orig, new_arch

    def delete_document_files(
        self,
        relative_path: str,
        document_id: Optional[int] = None,
    ) -> None:
        """Delete all files associated with a document (original, archive, thumbnail)."""
        # Original
        orig = self.config.originals_dir / relative_path
        if orig.exists():
            orig.unlink()
            logger.info("Deleted original: %s", orig)

        # Archive
        archive_path = self.config.archive_dir / Path(relative_path).with_suffix(".pdf")
        if archive_path.exists():
            archive_path.unlink()
            logger.info("Deleted archive: %s", archive_path)

        # Thumbnail
        if document_id:
            for ext in [".png", ".jpg", ".webp"]:
                thumb = self.config.thumbnail_dir / f"{document_id}{ext}"
                if thumb.exists():
                    thumb.unlink()
                    logger.info("Deleted thumbnail: %s", thumb)

    # -----------------------------------------------------------------------
    # Checksum
    # -----------------------------------------------------------------------

    @staticmethod
    def compute_checksum(file_path: str, algorithm: str = "sha256") -> str:
        """
        Compute file checksum.

        Args:
            file_path: Path to file.
            algorithm: Hash algorithm (default sha256).

        Returns:
            Hexadecimal digest string.
        """
        h = hashlib.new(algorithm)
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        return h.hexdigest()
