"""
Flashcard deck model.

Represents a collection of flashcards organized by topic or subject.
Supports tagging, visibility control, and AI generation tracking.
"""

from typing import Optional, List

from sqlalchemy import Boolean, String, Text, JSON, ARRAY
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base
from .mixins import TimestampMixin, SoftDeleteMixin, UserOwnedMixin


class Deck(Base, TimestampMixin, SoftDeleteMixin, UserOwnedMixin):
    """
    Flashcard deck model.

    A deck is a collection of flashcards grouped by topic, subject,
    or any other organizational scheme chosen by the user.
    """

    __tablename__ = "decks"

    # Primary Key
    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True,
        doc="Primary key"
    )

    # Basic Information
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Name of the deck"
    )

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        default=None,
        doc="Optional description of the deck's content or purpose"
    )

    # Organization
    tags: Mapped[Optional[List[str]]] = mapped_column(
        ARRAY(String),
        nullable=True,
        default=None,
        doc="Tags for categorization (PostgreSQL array type)"
    )

    # Visibility
    is_public: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        doc="Whether the deck is publicly visible"
    )

    # AI Generation Tracking
    ai_generated: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        doc="Whether this deck was generated by AI"
    )

    ai_metadata: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        default=None,
        doc="Metadata about AI generation (model used, prompt, etc.)"
    )

    # Relationships
    # flashcards: One-to-many with Flashcard (defined in flashcard.py)
    # user: Many-to-one with User (provided by UserOwnedMixin)

    def __repr__(self) -> str:
        """String representation of Deck."""
        return f"<Deck(id={self.id}, name='{self.name}', user_id={self.user_id})>"
