"""
Document model.

Uploaded documents (PDF, DOCX, etc.) with processing status tracking.
Integrates with Gemini Files API and vector embeddings.
"""

from datetime import date, datetime
from typing import Optional
import enum

from sqlalchemy import (
    String,
    Integer,
    Date,
    DateTime,
    Enum as SQLEnum,
    Text,
    Boolean,
    ForeignKey,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base
from .mixins import TimestampMixin, SoftDeleteMixin, UserOwnedMixin


class ProcessingStatus(str, enum.Enum):
    """Enum for document processing states."""

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class Document(Base, TimestampMixin, SoftDeleteMixin, UserOwnedMixin):
    """
    Document model for file uploads.

    Tracks uploaded documents through their processing lifecycle:
    upload → text extraction → chunking → embedding → indexing
    """

    __tablename__ = "documents"

    # Primary Key
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True, doc="Primary key")

    # File Information
    filename: Mapped[str] = mapped_column(String(255), nullable=False, doc="Original filename")

    file_path: Mapped[str] = mapped_column(
        String(500), nullable=False, doc="Path to stored file on disk"
    )

    file_type: Mapped[str] = mapped_column(
        String(50), nullable=False, doc="File type/extension (e.g., 'pdf', 'docx')"
    )

    file_size: Mapped[int] = mapped_column(Integer, nullable=False, doc="File size in bytes")

    # Content Hash for Deduplication (SHA256)
    content_hash: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,  # Nullable for migration; backfill existing docs later
        index=True,
        doc="SHA256 hash of file content for duplicate detection",
    )

    # -------------------------------------------------------------------------
    # DMS Architecture Fields (Phase 1)
    # -------------------------------------------------------------------------

    mime_type: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True, index=True,
        doc="Detected MIME type (e.g., 'application/pdf')",
    )

    archive_path: Mapped[Optional[str]] = mapped_column(
        String(500), nullable=True,
        doc="Path to PDF/A archive copy (generated by parser)",
    )

    archive_checksum: Mapped[Optional[str]] = mapped_column(
        String(64), nullable=True,
        doc="SHA256 checksum of archive file for integrity",
    )

    original_filename: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True,
        doc="Original filename as uploaded (before renaming)",
    )

    archive_serial_number: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True, unique=True,
        doc="Sequential archive number (ASN) for physical filing",
    )

    created_date: Mapped[Optional[date]] = mapped_column(
        Date, nullable=True,
        doc="Document creation date (extracted by parser or set by user)",
    )

    # -------------------------------------------------------------------------
    # DMS Classification Fields (Phase 3)
    # -------------------------------------------------------------------------

    correspondent_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("correspondents.id", ondelete="SET NULL"),
        nullable=True, index=True,
        doc="Auto-assigned correspondent (sender/receiver)",
    )

    document_type_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("document_types.id", ondelete="SET NULL"),
        nullable=True, index=True,
        doc="Auto-assigned document type (Invoice, Contract, etc.)",
    )

    storage_path_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("storage_paths.id", ondelete="SET NULL"),
        nullable=True, index=True,
        doc="Template-based storage path for file organization",
    )

    # Gemini Files API Integration
    gemini_file_uri: Mapped[Optional[str]] = mapped_column(
        String(500), nullable=True, default=None, doc="URI of file uploaded to Gemini Files API"
    )

    gemini_file_expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        doc="Expiration timestamp for Gemini file (48 hours after upload)",
    )

    # Processing Status
    processing_status: Mapped[ProcessingStatus] = mapped_column(
        SQLEnum(ProcessingStatus, native_enum=False),
        default=ProcessingStatus.PENDING,
        nullable=False,
        index=True,
        doc="Current processing status",
    )

    # Content Metadata
    page_count: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True, default=None, doc="Number of pages (for PDFs)"
    )

    word_count: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True, default=None, doc="Approximate word count"
    )

    ocr_performed: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, doc="Whether OCR was used to extract text"
    )

    file_metadata: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True, default=None, doc="Additional metadata (author, creation date, etc.)"
    )

    content_text: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, default=None, doc="Extracted text content from the document"
    )

    # User Annotations & Classification
    sector: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True, default="Uncategorized", doc="User-defined sector/category"
    )

    notes: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, default=None, doc="User notes attached to this document"
    )

    # AI-Generated Content (cached)
    ai_summary: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, default=None, doc="AI-generated summary of the document"
    )

    # Reading Progress (0.0 to 1.0)
    reading_progress: Mapped[Optional[float]] = mapped_column(
        nullable=True, default=0.0, doc="Reading progress (0.0 = start, 1.0 = finished)"
    )

    # -------------------------------------------------------------------------
    # Folder Organization (Phase 0)
    # -------------------------------------------------------------------------

    # Folder this document belongs to (null = Inbox)
    folder_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("document_folders.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="Folder ID (null = Inbox)",
    )

    # Provenance tracking for documents created from chat
    source_metadata: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True, default=None, doc="Source info: {chat_session_id, message_id}"
    )

    # Pin document to top of folder
    is_pinned: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, doc="Pin document to top of list"
    )

    # Archive state (separate from folder location)
    is_archived: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, doc="Document is archived"
    )

    # Favorite flag for quick access
    is_favorite: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, doc="Favorite flag"
    )
    # ----------------------------------------------------------------------

    # -------------------------------------------------------------------------
    # Relationships
    # -------------------------------------------------------------------------

    # Folder relationship
    folder = relationship(
        "DocumentFolder",
        back_populates="documents",
        foreign_keys=[folder_id],
    )

    # Classification relationships (Phase 3)
    correspondent = relationship("Correspondent", back_populates="documents")
    document_type = relationship("DocumentType", back_populates="documents")
    storage_path = relationship("StoragePath", back_populates="documents")
    tags = relationship("Tag", secondary="document_tags", back_populates="documents", lazy="selectin")

    # Other relationships
    # chunks: One-to-many with DocumentChunk (defined in document_chunk.py)
    # user: Many-to-one with User (from UserOwnedMixin)

    def __repr__(self) -> str:
        """String representation of Document."""
        return (
            f"<Document(id={self.id}, filename='{self.filename}', "
            f"status={self.processing_status.value})>"
        )

    @property
    def is_processed(self) -> bool:
        """Check if document processing is complete."""
        return self.processing_status == ProcessingStatus.COMPLETED

    @property
    def gemini_file_expired(self) -> bool:
        """Check if Gemini file has expired."""
        if not self.gemini_file_expires_at:
            return True
        from datetime import datetime, timezone

        return datetime.now(timezone.utc) > self.gemini_file_expires_at
