#!/usr/bin/env python3
"""
Purge Test Telemetry Data

Removes all synthetic telemetry data generated by generate_telemetry_data.py.
Identifies test data by the 'synthetic_' prefix in source_event_id.

CAUTION: This will permanently delete telemetry logs.
"""

import asyncio
import sys
from pathlib import Path
from sqlalchemy import text

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.db.session import AsyncSessionLocal


async def purge_synthetic_data():
    """Remove all synthetic telemetry data."""
    print("=" * 60)
    print("PURGE SYNTHETIC TELEMETRY DATA")
    print("=" * 60)
    print()

    async with AsyncSessionLocal() as session:
        # Count synthetic records
        result = await session.execute(
            text(
                "SELECT COUNT(*) FROM intelligence_adaptation_log WHERE source_event_id LIKE 'synthetic_%'"
            )
        )
        count = result.scalar()

        print(f"Found {count} synthetic telemetry records")

        if count == 0:
            print("✅ No synthetic data to purge")
            return

        # Delete synthetic records
        result = await session.execute(
            text("DELETE FROM intelligence_adaptation_log WHERE source_event_id LIKE 'synthetic_%'")
        )
        await session.commit()

        print(f"✅ Purged {count} synthetic records")

        # Verify
        result = await session.execute(text("SELECT COUNT(*) FROM intelligence_adaptation_log"))
        remaining = result.scalar()

        print(f"📊 Remaining telemetry records: {remaining}")

    print()
    print("=" * 60)
    print("PURGE COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(purge_synthetic_data())
