"""
Rasterized document parser — PDFs and images via OCR.

Weight: 0 (highest priority — this is the primary parser for PDFs).

Wraps Synapse's existing OcrProcessor (488 lines) and adds:
- Archive PDF/A generation passthrough
- Date extraction from content
- Structured metadata extraction

Sourced from Paperless-ngx RasterisedDocumentParser.
"""

import logging
from typing import Optional

from .base import BaseDocumentParser
from .utils import parse_date_from_text

logger = logging.getLogger(__name__)

SUPPORTED_MIME_TYPES = {
    "application/pdf",
    "image/jpeg",
    "image/png",
    "image/tiff",
    "image/bmp",
    "image/gif",
    "image/webp",
}
WEIGHT = 0  # Highest priority for PDFs


class RasterizedDocumentParser(BaseDocumentParser):
    """
    PDF + image parser using OCRmyPDF / Tesseract.

    Wraps Synapse's existing OcrProcessor and adds:
    - Archive PDF/A generation (via OCRmyPDF output_type)
    - Sidecar text extraction
    - Safe fallback on OCR failure
    - Date extraction from content
    """

    def parse(self, file_path: str, mime_type: str, filename: str) -> None:
        """Parse PDF/image file using OCR processor."""
        from app.services.ocr.processor import OcrProcessor

        with OcrProcessor() as processor:
            result = processor.process_file(file_path, mime_type)

            self._text = result.get("text", "")
            self._page_count = result.get("page_count")

            # output_pdf is the PDF/A archive generated by OCRmyPDF
            # (added in Step 2 of this implementation)
            self._archive_path = result.get("output_pdf")

            # Extract metadata from PDF info dict
            if processor.is_pdf(mime_type):
                self._metadata = self._extract_pdf_metadata(file_path)

        # Date extraction from content + filename
        self._date = parse_date_from_text(self._text or "", filename)

        logger.info(
            "Parsed %s: %d pages, %d chars, archive=%s",
            filename,
            self._page_count or 0,
            len(self._text or ""),
            "yes" if self._archive_path else "no",
        )

    def get_thumbnail(self, file_path: str, mime_type: str) -> Optional[str]:
        """Generate thumbnail using existing Synapse thumbnail generator."""
        try:
            from app.services.document.service import generate_thumbnail
            return generate_thumbnail(file_path, mime_type)
        except Exception as e:
            logger.warning("Thumbnail generation failed for %s: %s", file_path, e)
            return None

    def _extract_pdf_metadata(self, file_path: str) -> dict:
        """
        Extract PDF metadata (author, title, creation date, etc.).

        Uses pypdf which is already a Synapse dependency.
        """
        metadata = {}
        try:
            from pypdf import PdfReader
            reader = PdfReader(file_path)
            info = reader.metadata
            if info:
                if info.title:
                    metadata["title"] = info.title
                if info.author:
                    metadata["author"] = info.author
                if info.subject:
                    metadata["subject"] = info.subject
                if info.creator:
                    metadata["creator"] = info.creator
                if info.creation_date:
                    metadata["creation_date"] = str(info.creation_date)
        except Exception as e:
            logger.debug("PDF metadata extraction failed: %s", e)
        return metadata
