"""add_document_notes_sector_summary_fields

Revision ID: 29017093e61c
Revises: add_ocr_performed
Create Date: 2025-12-21 17:19:36.010602+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29017093e61c'
down_revision = 'add_ocr_performed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.Enum('TUTOR', 'DOCUMENT', 'QUIZ', 'CHAT', 'GENERAL', name='agenttype', native_enum=False), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('operation_type', sa.Enum('CHAT', 'GENERATION', 'ANALYSIS', 'SUMMARIZATION', 'QUESTION_ANSWERING', 'TOOL_USE', 'PLANNING', name='agentoperationtype', native_enum=False), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tool_calls_count', sa.Integer(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('context_used', sa.Boolean(), nullable=False),
    sa.Column('grounding_used', sa.Boolean(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_metrics_agent_name'), 'agent_metrics', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_metrics_agent_type'), 'agent_metrics', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_metrics_created_at'), 'agent_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_metrics_error_type'), 'agent_metrics', ['error_type'], unique=False)
    op.create_index(op.f('ix_agent_metrics_model_used'), 'agent_metrics', ['model_used'], unique=False)
    op.create_index(op.f('ix_agent_metrics_operation_type'), 'agent_metrics', ['operation_type'], unique=False)
    op.create_index(op.f('ix_agent_metrics_success'), 'agent_metrics', ['success'], unique=False)
    op.create_index(op.f('ix_agent_metrics_user_id'), 'agent_metrics', ['user_id'], unique=False)
    op.alter_column('activity_logs', 'activity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('VIEW', 'CREATE', 'UPDATE', 'DELETE', 'REVIEW', 'COMPLETE', 'UPLOAD', 'DOWNLOAD', 'SHARE', 'SEARCH', name='activitytype', native_enum=False),
               existing_nullable=False)
    op.alter_column('activity_logs', 'module',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FLASHCARDS', 'NOTES', 'DOCUMENTS', 'QUIZZES', 'CHAT', 'STUDY', 'ANALYTICS', name='moduletype', native_enum=False),
               existing_nullable=False)
    op.alter_column('activity_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_activity_logs_user_created', table_name='activity_logs')
    op.alter_column('chat_messages', 'function_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chat_messages', 'grounding_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'context_modules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('decks', 'ai_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('document_chunks', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('documents', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('reading_progress', sa.Float(), nullable=True))
    op.alter_column('documents', 'ocr_performed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'file_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('links', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NOTE', 'DECK', 'FLASHCARD', 'DOCUMENT', 'QUIZ', 'CHAT_SESSION', name='entitytype', native_enum=False),
               existing_nullable=False)
    op.alter_column('links', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NOTE', 'DECK', 'FLASHCARD', 'DOCUMENT', 'QUIZ', 'CHAT_SESSION', name='entitytype', native_enum=False),
               existing_nullable=False)
    op.alter_column('links', 'link_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.Enum('MANUAL', 'MENTION', 'DERIVED', 'SUGGESTED', 'SEMANTIC', name='linktype', native_enum=False),
               existing_nullable=False)
    op.alter_column('links', 'strength',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('links', 'link_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_links_user_id'), 'links', ['user_id'], unique=False)
    op.alter_column('quiz_attempts', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('quizzes', 'source_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('study_sessions', 'modules_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('study_sessions', 'performance_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('synapse_tasks', 'task_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PROCESS_DOCUMENT', 'INGEST_RAG', 'BATCH_INGEST', 'SEND_EMAIL', 'GENERATE_REPORT', 'CLEANUP', 'RETRY_WEBHOOKS', 'REBUILD_INDEX', 'OTHER', name='taskname', native_enum=False),
               existing_nullable=True)
    op.alter_column('synapse_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               type_=sa.Enum('AUTO', 'SCHEDULED', 'MANUAL', name='tasktype', native_enum=False),
               existing_nullable=False)
    op.alter_column('synapse_tasks', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               type_=sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('synapse_tasks', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('synapse_tasks_task_id_key', 'synapse_tasks', type_='unique')
    op.drop_index('ix_synapse_tasks_task_id', table_name='synapse_tasks')
    op.create_index(op.f('ix_synapse_tasks_task_id'), 'synapse_tasks', ['task_id'], unique=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String(length=100)),
               existing_nullable=False)
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhooks', 'total_deliveries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhooks', 'successful_deliveries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhooks', 'failed_deliveries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_webhooks_events', table_name='webhooks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_webhooks_events', 'webhooks', ['events'], unique=False, postgresql_using='gin')
    op.alter_column('webhooks', 'failed_deliveries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('webhooks', 'successful_deliveries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('webhooks', 'total_deliveries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.ARRAY(sa.String(length=100)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('webhook_events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_synapse_tasks_task_id'), table_name='synapse_tasks')
    op.create_index('ix_synapse_tasks_task_id', 'synapse_tasks', ['task_id'], unique=False)
    op.create_unique_constraint('synapse_tasks_task_id_key', 'synapse_tasks', ['task_id'])
    op.alter_column('synapse_tasks', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('synapse_tasks', 'status',
               existing_type=sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus', native_enum=False),
               server_default=sa.text("'PENDING'::character varying"),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('synapse_tasks', 'task_type',
               existing_type=sa.Enum('AUTO', 'SCHEDULED', 'MANUAL', name='tasktype', native_enum=False),
               server_default=sa.text("'auto'::character varying"),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('synapse_tasks', 'task_name',
               existing_type=sa.Enum('PROCESS_DOCUMENT', 'INGEST_RAG', 'BATCH_INGEST', 'SEND_EMAIL', 'GENERATE_REPORT', 'CLEANUP', 'RETRY_WEBHOOKS', 'REBUILD_INDEX', 'OTHER', name='taskname', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('study_sessions', 'performance_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('study_sessions', 'modules_used',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('quizzes', 'source_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('quiz_questions', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_links_user_id'), table_name='links')
    op.alter_column('links', 'link_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('links', 'strength',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.alter_column('links', 'link_type',
               existing_type=sa.Enum('MANUAL', 'MENTION', 'DERIVED', 'SUGGESTED', 'SEMANTIC', name='linktype', native_enum=False),
               server_default=sa.text("'manual'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('links', 'target_type',
               existing_type=sa.Enum('NOTE', 'DECK', 'FLASHCARD', 'DOCUMENT', 'QUIZ', 'CHAT_SESSION', name='entitytype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('links', 'source_type',
               existing_type=sa.Enum('NOTE', 'DECK', 'FLASHCARD', 'DOCUMENT', 'QUIZ', 'CHAT_SESSION', name='entitytype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('documents', 'file_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'ocr_performed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('documents', 'reading_progress')
    op.drop_column('documents', 'ai_summary')
    op.drop_column('documents', 'notes')
    op.drop_column('documents', 'sector')
    op.alter_column('document_chunks', 'chunk_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decks', 'ai_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'context_modules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chat_messages', 'grounding_sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chat_messages', 'function_calls',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_activity_logs_user_created', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('activity_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('activity_logs', 'module',
               existing_type=sa.Enum('FLASHCARDS', 'NOTES', 'DOCUMENTS', 'QUIZZES', 'CHAT', 'STUDY', 'ANALYTICS', name='moduletype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('activity_logs', 'activity_type',
               existing_type=sa.Enum('VIEW', 'CREATE', 'UPDATE', 'DELETE', 'REVIEW', 'COMPLETE', 'UPLOAD', 'DOWNLOAD', 'SHARE', 'SEARCH', name='activitytype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_metrics_user_id'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_success'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_operation_type'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_model_used'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_error_type'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_created_at'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_agent_type'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_agent_name'), table_name='agent_metrics')
    op.drop_table('agent_metrics')
    # ### end Alembic commands ###
