"""Add intelligence_adaptation_log table

Revision ID: 9aee2bc642bc
Revises: 715e1be1a0d9
Create Date: 2026-01-10 17:34:33.323995+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aee2bc642bc'
down_revision = '715e1be1a0d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_messages', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('chat_messages_bm25_idx', table_name='chat_messages', postgresql_with={'key_field': 'id'}, postgresql_using='bm25')
    op.drop_index('chat_messages_content_trgm_idx', table_name='chat_messages', postgresql_using='gin')
    op.drop_index('chat_sessions_title_trgm_idx', table_name='chat_sessions', postgresql_using='gin')
    op.alter_column('documents', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA256 hash of file content for duplicate detection',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA256 hash of file content for duplicate detection',
               existing_nullable=True)
    op.create_index('chat_sessions_title_trgm_idx', 'chat_sessions', ['title'], unique=False, postgresql_using='gin')
    op.create_index('chat_messages_content_trgm_idx', 'chat_messages', ['content'], unique=False, postgresql_using='gin')
    op.create_index('chat_messages_bm25_idx', 'chat_messages', ['id', 'content'], unique=False, postgresql_with={'key_field': 'id'}, postgresql_using='bm25')
    op.alter_column('chat_messages', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('chat_messages', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    # ### end Alembic commands ###
